<tr>
    <td><a href="?page=edit-tache&id=<?= $id ?>">Edit</a></td>
    <td><a href="?page=supp-tache&id=<?= $id ?>">Supprimer</a></td>
    <td><a href="?page=dupli-tache&id=<?= $id ?>">Duppliquer</a></td>
    <td><?= $tache['titre'] ?></td>
    <td><?= $tache['description'] ?></td>
    <td><?= $tache['priorite'] ?></td>
    <td><?= $tache['date-crea'] ?></td>
    <td><?= $tache['date-rea'] ?></td>
    <td><?= $tache['description'] ?></td>
    <td><?= $tache['commentaire'] ?></td>
</tr>