<div class="row">
    <div><a href="?page=creer-article">Nouvel article</a></div>
    <table>
        <tr>
            <td></td>
            <td></td>
            <td>Date</td>
            <td>Photo</td>
            <td>Titre</td>
            <td>Auteur</td>
            <td>Descriptif</td>
            <td></td>
        </tr>
    <?php
        require('apps/admin-article.php');
    ?>        
    </table>
</div>