<div class="row">
    <div><a href="?page=edit-tache&id=new">Nouvel article</a></div>
    <table>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>Titre</td>
            <td>Description</td>
            <td>Priorite</td>
            <td>Date de creation</td>
            <td>date realisation</td>
            <td>Description</td>
            <td>Commentaire</td>
        </tr>
    <?php
        require('apps/admin-article.php');
    ?>
    </table>
</div>