<!-- Ne pas supprimer ces boutons -->
<div>
    <select id="order">
        <option value="priorite" <?= $option_order[0] ?>>Prioritée</option>
        <option value="date-crea" <?= $option_order[1] ?>>Date de création</option>
        <option value="date-rea" <?= $option_order[2] ?>>Date de réalisation</option>
    </select>

    <select id="order-by">
        <option value="asc" <?= $option_order_by[0] ?>>Croissant</option>
        <option value="desc" <?= $option_order_by[1] ?>>Décroissant</option>
    </select>   
</div>

<div class="row">
<?php
    require('apps/tache.php');
?>
</div>