<p>Register <span class="message"><?= $form['message'] ?></span></p>
<form method="POST" class="register-form" enctype="multipart/form-data" action="#edit-tache" id="edit-tache">
    <input type="hidden"  name="form[id]" value="<?= $id ?>">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="titre">Titre</label>
                <input type="text" id="titre" name="form[titre]" value="<?= $form['titre']['value'] ?>" class="<?= $form['titre']['class'] ?>">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="description">Description</label>
                <textarea id="description" name="form[description]"  class="<?= $form['description']['class'] ?>"><?= $form['description']['value'] ?></textarea>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="priorite">Priorite</label>
                <select id="priorite" name="form[priorite]" value="<?= $form['priorite']['value'] ?>" class="<?= $form['priorite']['class'] ?>">
                    <option value="0" <?= $option_priority[0] ?>>0</option>
                    <option value="1" <?= $option_priority[1] ?>>1</option>
                    <option value="2" <?= $option_priority[2] ?>>2</option>
                    <option value="3" <?= $option_priority[3] ?>>3</option>
                </select>                
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="date-crea">Date de creation</label>
                <input type="date-crea" id="date-crea" name="form[date-crea]" value="<?= $form['date-crea']['value'] ?>" class="<?= $form['date-crea']['class'] ?>">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="date-rea">Date de réalisation</label>
                <input type="date-rea" id="date-rea" name="form[date-rea]" value="<?= $form['date-rea']['value'] ?>" class="<?= $form['date-rea']['class'] ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <label for="commentaire">Commentaire</label>
                <textarea id="commentaire" name="form[commentaire]"  class="<?= $form['commentaire']['class'] ?>"><?= $form['commentaire']['value'] ?></textarea>
            </div>
        </div>
    </div>    

     <div class="row">
        <div class="col-sm-12 submit">   
            <button type="submit" class="button">Modifier</button>   
        </div>
    </div>

</form>