<!-- Page à traiter. laisser le HTML modifier le CSS -->
<div class="row">
    <div><a href="?page=edit-tache&id=new">Nouvelle Tache</a></div>
    <table>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>Titre</td>
            <td>Description</td>
            <td>Priorite</td>
            <td>Date de creation</td>
            <td>date realisation</td>
            <td>Description</td>
            <td>Commentaire</td>
        </tr>
    <?php
        require('apps/list-tache.php');
    ?>
    </table>
</div>