<div class="header">
    <div class="header-login-message">
        <?= $login_info['message'] ?>
        <a href="?page=<?= $login_info['page'] ?>"><span class="glyphicon glyphicon-log-<?= $login_info['icon'] ?>" aria-hidden="true"></span></a>
    </div>
    <nav class="navbar navbar-inverse">
            <div class="row">                        
                <div class="col-sm-12 col-md-4">
                    <a href="?page=home">
                        <img src="<?= IMAGE_PATH ?>sprite.png" alt="">
                    </a>
                </div>
                <div class="col-sm-12 col-md-8">
                    <ul class="nav navbar-nav">
                        <?php require('apps/display-nav-menu.php'); ?> 
                    </ul>
                </div>      
            </div>
    </nav>    
</div>