<p>Log in <span class="message"><?= $form['message'] ?></span></p>
<form method="POST" class="register-form" enctype="multipart/form-data" method="#login" id="login">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="login">Login</label>
                <input type="text" id="login" name="form[login]" value="<?= $form['login']['value'] ?>" class="<?= $form['login']['class'] ?>"> 
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="password">Pass word</label>
                <input type="password" id="password" name="form[password]" value="<?= $form['password']['value'] ?>" class="<?= $form['password']['class'] ?>"> 
            </div>
        </div>
    </div>

     <div class="row">
        <div class="col-sm-12 submit">   
            <button type="submit" class="button">Send</button>   
        </div>
    </div>    
</form>