<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="public/css/bootstrap.min.css" />
         <link rel="stylesheet" type="text/css" href="public/css/style.css">
        <script src="<?= $js_path ?>jquery-2.2.3.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/main.js"></script>
        <script src="js/less.min.js"></script>
        <link href='https://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
        <title>Blog Photos</title>
    </head>
    <body>
        <div class="header">
            <nav>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Register</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </nav>
        </div>
        <div class="container">
            <h1>Article</h1>
            <div class="wrap">
                <div class="gauche">
                    <img src="public/images/image_1.jpg"/>
                </div>
                <div class="droite">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos tempore quos maxime fugit, quidem accusamus perferendis. Dolorum est, unde dicta. Quo nam at consequatur earum, sequi ratione nemo labore.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed repellendus optio quaerat eos voluptate sunt similique ipsa. Ut unde praesentium architecto. Aut harum impedit, magnam non, esse quam repudiandae fugit?
                    </p>
                    <div class="author">Admin</div>
                    <div class="date"><?= date("m/d/Y H\hi")?></div>
                </div>
            </div>
            <h1>Article</h1>
            <div class="wrap">
                <div class="gauche">
                    <img src="public/images/image_2.jpg"/>
                </div>
                <div class="droite">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos tempore quos maxime fugit, quidem accusamus perferendis. Dolorum est, unde dicta. Quo nam at consequatur earum, sequi ratione nemo labore.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed repellendus optio quaerat eos voluptate sunt similique ipsa. Ut unde praesentium architecto. Aut harum impedit, magnam non, esse quam repudiandae fugit?</p>
                    <div class="author">Admin</div>
                    <div class="date"><?= date("m/d/Y H\hi")?></div>
                </div>
            </div>
            <h1>Article</h1>
            <div class="wrap">
                <div class="gauche">
                    <img src="public/images/image_3.jpg"/>
                </div>
                <div class="droite">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos tempore quos maxime fugit, quidem accusamus perferendis. Dolorum est, unde dicta. Quo nam at consequatur earum, sequi ratione nemo labore.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed repellendus optio quaerat eos voluptate sunt similique ipsa. Ut unde praesentium architecto. Aut harum impedit, magnam non, esse quam repudiandae fugit?</p>
                    <div class="author">Admin</div>
                    <div class="date"><?= date("m/d/Y H\hi")?></div>
                </div>
            </div>
        </div>
        <div class="footer">
            <p class="blog">Blog Photos - 2016</p>
            <nav>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">About</a></li>
                </ul>
            </nav>
        </div>
   </body>
</html>