<p>Register <span class="message"><?= $form['message'] ?></span></p>
<form method="POST" class="register-form" enctype="multipart/form-data" action="#register" id="register">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="login">login</label>
                <input type="text" id="login" name="form[login]" value="<?= htmlentities ($form['login']['value']) ?>" class="<?= htmlentities ($form['login']['class']) ?>">
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="email">Mail</label>
                <input type="email" id="email" name="form[email]" value="<?= htmlentities ($form['email']['value']) ?>" class="<?= htmlentities ($form['email']['class']) ?>">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="password">Pass word</label>
                <input type="password" id="password" name="form[password]" value="<?= htmlentities ($form['password']['value']) ?>" class="<?= htmlentities ($form['password']['class']) ?>">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="confirmpassword">Confirme Pass word</label>
                <input type="password" id="confirm-password" name="form[confirm-password]" value="<?= htmlentities ($form['confirm-password']['value']) ?>" class="<?= htmlentities ($form['confirm-password']['class']) ?>">
            </div>
        </div>
    </div>

     <div class="row">
        <div class="col-sm-12 submit">   
            <button type="submit" class="button">Send</button>   
        </div>
    </div>

</form>