<p>Register <span class="message"><?= $form['message'] ?></span></p>
<form method="POST" class="register-form" enctype="multipart/form-data" action="#register" id="register">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="name">Name</label>
                <input type="text" id="name" name="form[name]" value="<?= $form['name']['value'] ?>" class="<?= $form['name']['class'] ?>">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="firstname">First Name</label>
                <input type="text" id="firstname" name="form[firstname]" value="<?= $form['firstname']['value'] ?>" class="<?= $form['firstname']['class'] ?>">
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="mail">Mail</label>
                <input type="email" id="mail" name="form[mail]" value="<?= $form['mail']['value'] ?>" class="<?= $form['mail']['class'] ?>">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <label for="password">Pass word</label>
                <input type="password" id="password" name="form[password]" value="<?= $form['password']['value'] ?>" class="<?= $form['password']['class'] ?>">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <label for="confirmpassword">Confirme Pass word</label>
                <input type="password" id="confirm-password" name="form[confirm-password]" value="<?= $form['confirm-password']['value'] ?>" class="<?= $form['confirm-password']['class'] ?>">
            </div>
        </div>
    </div>

     <div class="row">
        <div class="col-sm-12 submit">   
            <button type="submit" class="button">Send</button>   
        </div>
    </div>

</form>