<form method="POST" class="register-form" enctype="multipart/form-data">

    <div class="row">
        <div class="col-sm-12">
            <input type="hidden"  name="id" value="<?= $id ?>">
            <label for="titre">Etes-vous sûre de vouloir supprimer cet article ?</label>
            <button type="submit" name="confirme" value="yes" class="button">Oui</button>
            <button type="submit" name="confirme" value="no" class="button">Non</button>  
           
        </div>
    </div>

</form>